GRAPH_NAME = dielFilterV2clx
GRAPH_URL  = https://suitesparse-collection-website.herokuapp.com/MM/Dziekonski/dielFilterV2clx.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk
