GRAPH_NAME = fem_hifreq_circuit
GRAPH_URL  = https://suitesparse-collection-website.herokuapp.com/MM/Lee/fem_hifreq_circuit.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk
