GRAPH_NAME = soc-sign-Slashdot090221
GRAPH_URL  = https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-Slashdot090221.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk
