GRAPH_NAME = hugebubbles-00010
GRAPH_URL = https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugebubbles-00010.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk
