GRAPH_NAME = kron_g500-logn21
GRAPH_URL  = https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/kron_g500-logn21.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk
