GRAPH_NAME = hugetrace-00020
GRAPH_URL = https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/hugetrace-00020.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk
