GRAPH_NAME = soc-sign-epinions
GRAPH_URL  = https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-sign-epinions.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk
