GRAPH_NAME = coPapersCiteseer
GRAPH_URL  = https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coPapersCiteseer.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk