GRAPH_NAME = 3Dspectralwave
GRAPH_URL  = https://suitesparse-collection-website.herokuapp.com/MM/Sinclair/3Dspectralwave.tar.gz

include ../../common.mk
include ../../ufl.mk
include ../../convert.mk

