GRAPH_NAME = coAuthorsCiteseer
GRAPH_URL = https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/coAuthorsCiteseer.tar.gz

include ../../ufl.mk
include ../../common.mk
include ../../convert.mk
